sonar.projectKey=artswarit-local
sonar.projectName=artswarit-local

sonar.host.url=http://localhost:9000
sonar.token=sqa_9a04a011c086e1e0bb704f229de9c7c7edb05423

sonar.sources=src,supabase
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,build/**